# Generated by Django 4.2 on 2023-06-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-id']},
        ),
    ]
